using UnityEngine;
using System.Collections;


public class reklame : MonoBehaviour {

	// Use this for initialization

	void Start () {

		//UnityPluginForWindowsPhone.Class1.konstruktor ("ca-app-pub-6223160944701050/5027679925",true);
		//UnityPluginForWindowsPhone.Class1.loadCelozaslonsko ();

		//UnityPluginForWindowsPhone.Class1.createBanner (false,"ca-app-pub-6223160944701050/4726628723",true);
		UnityPluginForWindowsPhone.Class1.createBanner (false,"ca-app-pub-6223160944701050/4726628723",true,"MALE","2/15/2012 6:00:00 AM -7:00",true);
		//x.klas ();

	}
	
	// Update is called once per frame
	void Update () {
		//UnityPluginForWindowsPhone.Class1.showCelozaslonsko ();
	}

	public void prizgi(){
		UnityPluginForWindowsPhone.Class1.setBannerVisibility (true);
	}

	public void ugasni(){
		UnityPluginForWindowsPhone.Class1.setBannerVisibility (false);
	}

	public void dol(){
		UnityPluginForWindowsPhone.Class1.setBannerAlignment ("BOTTOM");
	}

	public void gor(){
		UnityPluginForWindowsPhone.Class1.setBannerAlignment ("TOP");
	}
}
